ProyectoLenguajes/ProyectoLenguajes/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using ProyectoLenguajes.Models;
using System.Diagnostics;

namespace ProyectoLenguajes.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ProyectoLenguajes/ProyectoLenguajes/Controllers/SuperAdminController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using ProyectoLenguajes.Data;
using ProyectoLenguajes.Models;
using ProyectoLenguajes.Models.Domain;
using ProyectoLenguajes.Models.DTO;
using ProyectoLenguajes.Repositories.Abstract;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using System;
using System.Data;
using System.Security.Claims;

namespace ProyectoLenguajes.Controllers
{
    //Poner en TestUCRContext.cs:
    //    public virtual DbSet<Errors> ERRORs { get; set; }

    //    modelBuilder.Entity<Errors>(entity =>
    //    {
    //        entity.HasNoKey();
    //        entity.Property(e => e.error);
                
    //    });
public class SuperAdminController : Controller
    {
        private TestUCRContext db = new TestUCRContext(); //We call our database
        private readonly IUserAuthenticationService _service; //We call the utilities of the other base
        private readonly UserManager<ApplicationUser> userManager; //We call application user
        public SuperAdminController(IUserAuthenticationService service, UserManager<ApplicationUser> userManager)
        {
            this._service = service;
            this.userManager = userManager;
        }

        [Authorize(Roles = "superA")]
        public IActionResult Display()
        {
            var personList = new List<ACCOUNT>();
            //var error = new Errors();
            try
            {//To obtain the username of the migration database and search for it in our database
                var userId = User.FindFirstValue(ClaimTypes.Name);
                var d = ViewBag.Error = userId;

                personList = db.ACCOUNTs.FromSqlRaw("exec dbo.GetAdminsAccounts").ToList();//get only admins
                return View(personList);

            }
            catch (Exception ex)
            {
                //var result = db.ERRORs.FromSqlRaw("exec dbo.GetAllAccounts").ToList();
                //var a = ViewBag.Error = result[0].error.ToString();
                return View(personList);
            }

        }

        [Authorize(Roles = "superA")]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(RegistrationModel model)
        {
            //var error = new Errors();
            try
            {
                //If it's not valid, don't believe it.
                if (!ModelState.IsValid)
                {
                    return View(model);
                }
                //to get the migration username
                var userId = User.FindFirstValue(ClaimTypes.Name);

                var parameter = new List<SqlParameter>();
                parameter.Add(new SqlParameter("@userID", userId));
                parameter.Add(new SqlParameter("@name", model.Name));
                parameter.Add(new SqlParameter("@email", model.Email));
                parameter.Add(new SqlParameter("@roll", "admin"));
                parameter.Add(new SqlParameter("@userName", model.UserName));
                parameter.Add(new SqlParameter("@password", model.Password));

                var rs = Task.Run(() => db.Database //we pass the parameters to the SP
                .ExecuteSqlRaw(@"exec InsertAccounts @userID, @name, @email, @roll, @userName, @password", parameter.ToArray()));

                model.Role = "admin";//we forcefully assign the role of admin
                var result = await _service.RegistrationAsync(model); //the method we did is called
                TempData["msg"] = result.Message;

                return RedirectToAction(nameof(Create));
            }
            catch (Exception ex)
            {
                //var rr = db.ERRORs.FromSqlRaw("exec InsertAccounts @userID, @name, @email, @roll, @userName, @password").ToList();
                //var a = ViewBag.Error = rr[0].error.ToString();
                return View();
            }
        }

        [Authorize(Roles = "superA")]
        public ActionResult Details(int id)
        {
            var acc = db.ACCOUNTs.Find(id);
            return View(acc);
        }

        [Authorize(Roles = "superA")]
        public ActionResult Edit(int id)
        {
            var person = db.ACCOUNTs.Find(id);
            return View(person);
        }

        // POST: PersonController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, ACCOUNT acc)//Viene con el username nuevo
        {
            try
            {
                //get all public fields of the model
                var fields = acc.GetType().GetProperties();

                foreach (var field in fields)
                {
                    var value = field.GetValue(acc);
                    if (value == null)
                    {
                        //if a null field is found, return the view with an error message
                        TempData["msg"] = "You cannot leave fields empty.";
                        return View();
                    }
                }
                ACCOUNT act = db.ACCOUNTs.Find(acc.idAccount);//It comes with the old username

                var userId = User.FindFirstValue(ClaimTypes.Name);

                var parameter = new List<SqlParameter>();
                parameter.Add(new SqlParameter("@userID", userId));
                parameter.Add(new SqlParameter("@idAccount", acc.idAccount));
                parameter.Add(new SqlParameter("@name", acc.name));
                parameter.Add(new SqlParameter("@email", acc.email));
                parameter.Add(new SqlParameter("@username", acc.userName));
                parameter.Add(new SqlParameter("@password", acc.password));
                parameter.Add(new SqlParameter("@img", acc.img));

                var rs = Task.Run(() => db.Database
                .ExecuteSqlRaw(@"exec UpdateAccount @userID, @idAccount, @name, @email, @username, @password, @img", parameter.ToArray()));

                var result = await _service.UpdateUserAsync(acc, act.userName); //the method we did is called
                TempData["msg"] = result.Message;

                return RedirectToAction(nameof(Edit));

            }
            catch (Exception e)
            {
                //var rr = db.ERRORs.FromSqlRaw("exec UpdateAccount @userID, @idAccount, @name, @email, @username, @password, @img").ToList();
                //var a = ViewBag.Error = rr[0].error.ToString();
                return View();
            }
        }

        [Authorize(Roles = "superA")]
        public ActionResult Delete(int id)
        {
            var acc = db.ACCOUNTs.Find(id);
            return View(acc);
        }

        // POST: PersonController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id, ACCOUNT acc)
        {
            try
            {
                ACCOUNT act = db.ACCOUNTs.Find(acc.idAccount);//to find the account with this id

                var result = await _service.DeleteUserAsync(act); //the method we did is called
                TempData["msg"] = result.Message;

                var userId = User.FindFirstValue(ClaimTypes.Name);

                var parameter = new List<SqlParameter>();
                parameter.Add(new SqlParameter("@userID", userId));
                parameter.Add(new SqlParameter("@idAccount", act.idAccount));

                //to use the SP
                var rs = Task.Run(() => db.Database
                .ExecuteSqlRaw(@"exec DeleteAccount @userID, @idAccount", parameter.ToArray()));

                return RedirectToAction(nameof(Delete));
            }
            catch (Exception ex)
            {
                //var rr = db.ERRORs.FromSqlRaw("exec DeleteAccount @userID, @idAccount").ToList();
                //var a = ViewBag.Error = rr[0].error.ToString();
                return View();
            }
        }

        //Here we uses the ICONAPI
        [Authorize(Roles = "superA")]
        public ActionResult FilterIcons()
        {
            var iconList = new List<Models.Icon>();
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri("https://localhost:7249/api/Icons");//The API service
                //HTTP GET
                var responseTask = client.GetAsync("Icons");
                responseTask.Wait();

                var result = responseTask.Result;

                if (result.IsSuccessStatusCode)
                {
                    var readTask = result.Content.ReadFromJsonAsync<List<Models.Icon>>();
                    readTask.Wait();

                    iconList = readTask.Result;
                }
                else //si la api arroja algun error
                {
                    return BadRequest("problemas");
                }
            }

            return Json(iconList);
        }

        [Authorize(Roles = "superA")]
        public ActionResult Home()
        {
            var userNameM = User.FindFirstValue(ClaimTypes.Name);
            var userNameC = ViewBag.UserName = userNameM;
            //here we find our account
            var id = db.ACCOUNTs
    .Where(a => a.userName == userNameM)
    .Select(a => a.idAccount)
    .FirstOrDefault();
            var acc = db.ACCOUNTs.Find(id);
            return View(acc);
        }

        [Authorize(Roles = "superA")]
        public IActionResult DownloadPDF()//to the pdf of admins
        {
            var userList = new List<ACCOUNT>();
            userList = db.ACCOUNTs.FromSqlRaw("exec dbo.GetAdminsAccounts").ToList();

            var documentpdf = Document.Create(container =>
            {
                container.Page(page =>
                {

                    page.Content().PaddingVertical(10).Column(col =>
                    {

ProyectoLenguajes/ProyectoLenguajes/Views/SuperAdmin/Create.cshtml
@model ProyectoLenguajes.Models.DTO.RegistrationModel
@{
    Layout = null;
}
@ViewBag.Error

<!DOCTYPE html>

<html>
<head>
    @*    <meta name="viewport" content="width=device-width" />
    *@
    <meta charset="UTF-8">
    <title>Registration</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/css/superadmin.css">

    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/jquery.slick/1.3.11/slick.css" />
    <link rel="stylesheet" type="text/css" href="slick/slick.css" />
    <link rel="stylesheet" type="text/css" href="slick/slick-theme.css" />
</head>
<body>
    <h1><center>Registration</center></h1>
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <form asp-action="Create" method="post">
                    @*                    <h3>Registration</h3>
                    *@                    <div class="form-group">
                        <label>Name</label>
                        <input type="text" class="form-control" asp-for="Name" />
                        <span class="text-danger" asp-validation-for="Name"></span>
                    </div>

                    <div class="form-group">
                        <label>UserName</label>
                        <input type="text" class="form-control" asp-for="UserName" />
                        <span class="text-danger" asp-validation-for="UserName"></span>
                    </div>

                    <div class="form-group">
                        <label>Email</label>
                        <input type="text" class="form-control" asp-for="Email" />
                        <span class="text-danger" asp-validation-for="Email"></span>
                    </div>

                    <div class="form-group">
                        <label>Password</label>
                        <input type="password" class="form-control" asp-for="Password" />
                        <span class="text-danger" asp-validation-for="Password"></span>
                    </div>

                    <div class="form-group">
                        <label>Password Confirm</label>
                        <input type="password" class="form-control" asp-for="PasswordConfirm" />
                        <span class="text-danger" asp-validation-for="PasswordConfirm"></span>
                    </div>

                    @if (TempData["msg"] != null)
                    {
                        <div class="form-group">
                            @TempData["msg"]
                        </div>
                    }

                    <button type="submit" class="btn btn-primary">SignUp</button>
                    <a class="btn btn-info" href="/SuperAdmin/Display">List</a>
                </form>
            </div>
        </div>
    </div>
</body>
</html>

ProyectoLenguajes/ProyectoLenguajes/Views/SuperAdmin/Details.cshtml
@model ProyectoLenguajes.Models.ACCOUNT

@{
    ViewData["Title"] = "Details";
}

<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Tangerine">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/css/superadmin.css">

    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/jquery.slick/1.3.11/slick.css" />
    <link rel="stylesheet" type="text/css" href="slick/slick.css" />
    <link rel="stylesheet" type="text/css" href="slick/slick-theme.css" />
</head>

<h1><center>@Model.userName</center></h1>

<div class="greater d-flex justify-content-center flex-wrap">

<div class="image">
    <img src=@Model.img>
</div>

<div>
    <h4><center>Personal Information</center></h4>

    <hr />
    <dl class="row">
        <dt class = "color1 col-sm-2">
            @Html.DisplayNameFor(model => model.name)
        </dt>
            <dd class="color1 col-sm-10">
            @Html.DisplayFor(model => model.name)
        </dd>
            <dt class="color1 col-sm-2">
            @Html.DisplayNameFor(model => model.email)
        </dt>
            <dd class="color1 col-sm-10">
            @Html.DisplayFor(model => model.email)
        </dd>
            <dt class="color1 col-sm-2">
            @Html.DisplayNameFor(model => model.roll)
        </dt>
            <dd class="color1 col-sm-10">
            @Html.DisplayFor(model => model.roll)
        </dd>
            <dt class="color1 col-sm-2">
            @Html.DisplayNameFor(model => model.userName)
        </dt>
            <dd class="color1 col-sm-10">
            @Html.DisplayFor(model => model.userName)
        </dd>
    </dl>
</div>
</div>
<div class="buttoms d-flex text-center" style="height: 100vh;">
    <a class="btn btn-info btn-primary m-2" asp-action="Edit" asp-route-id="@Model?.idAccount">Edit</a> |
    <a class="btn btn-info btn-primary m-2" href="/SuperAdmin/Display">Back to List</a>
</div>

ProyectoLenguajes/ProyectoLenguajes/Views/SuperAdmin/Display.cshtml
@model IEnumerable<ProyectoLenguajes.Models.ACCOUNT>
@using System.Security.Claims;
@using ProyectoLenguajes.Data;
@using Microsoft.AspNetCore.Mvc;
@using Microsoft.EntityFrameworkCore;
@{
    ViewData["Title"] = "Display";
    TestUCRContext db = new TestUCRContext();

    var userNameM = User.FindFirstValue(ClaimTypes.Name);//To get the username of current account
    var id = db.ACCOUNTs
    .Where(a => a.userName == userNameM)
    .Select(a => a.idAccount)
    .FirstOrDefault();//To get the id of de current account in our database
    var imge = db.ACCOUNTs
    .Where(a => a.userName == userNameM)
    .Select(a => a.img)
    .FirstOrDefault();//To get the img of the current account in our database
}

<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Tangerine">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
    
    <link rel="stylesheet" href="~/css/superadmin.css">

    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/jquery.slick/1.3.11/slick.css" />
    <link rel="stylesheet" type="text/css" href="slick/slick.css" />
    <link rel="stylesheet" type="text/css" href="slick/slick-theme.css" />


</head>

<body class="navbar navbar-expand-lg navbar-light bg-light">
    <header>
        <div class="container">
            <h2 class="title">Hello!</h2>

            <!--NAVBAR-->
            <nav class="navbar navbar-expand-sm navbar navbar-light">

                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#opciones" style="background-color: #DDE9F8">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="opciones">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link active" href="/SuperAdmin/Home" style="color: #ffffff;">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/SuperAdmin/Details/@id" style="color: #ffffff;">Profile</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/SuperAdmin/AboutOf" style="color: #ffffff;">About Of</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/SuperAdmin/Options" style="color: #ffffff;">Options</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/UserAuthentication/Logout" style="color: #ffffff;">Log Out</a>
                        </li>
                    </ul>
                </div>
            </nav>
        </div>
    </header>
    <hr />
    <h1><center>Accounts</center></h1>

    <p>
        <a asp-action="Create" class="btn btn-primary glyphicon glyphicon-plus-sign"></a>
    </p>
    <form asp-controller="SuperAdmin" asp-action="DownloadPDF">
        <button class="btn btn-success" type="submit" id="btnReport">Report</button>
    </form>
    <div class="table-responsive">
        <table class="table">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.name)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.email)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.roll)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.userName)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.password)
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.name)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.email)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.roll)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.userName)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.password)
                        </td>
                        <td>
                            <a asp-action="Edit" asp-route-id="@item.idAccount" class="btn btn-primary glyphicon glyphicon-pencil"></a> |
                            <a asp-action="Details" asp-route-id="@item.idAccount" class="btn btn-primary glyphicon glyphicon-user"></a> |
                            <a asp-action="Delete" asp-route-id="@item.idAccount" class="btn btn-primary glyphicon glyphicon-trash"></a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
    <!--JS-->
    <script type="text/javascript" src="//code.jquery.com/jquery-1.11.0.min.js"></script>
    <script type="text/javascript" src="//code.jquery.com/jquery-migrate-1.2.1.min.js"></script>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
</body>

ProyectoLenguajes/ProyectoLenguajes/Views/SuperAdmin/Home.cshtml
@model ACCOUNT
@using System.Security.Claims;
@using ProyectoLenguajes.Data;
@{
    ViewData["Title"] = "Home";
    TestUCRContext db = new TestUCRContext();

    var userNameM = User.FindFirstValue(ClaimTypes.Name);//To get the username of current account
    var id = db.ACCOUNTs
    .Where(a => a.userName == userNameM)
    .Select(a => a.idAccount)
    .FirstOrDefault();//To get the id of de current account in our database
}

<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" href="~/css/superadmin.css">
    <title>Tu Título</title>
    <style>
        body {
            padding: 1em;
            text-align: center;
        }

        .app-name {
            font-size: 24px;
            margin-bottom: 1em;
        }

        .button {
            display: inline-block;
            padding: 12px 24px;
            font-size: 18px;
            font-weight: bold;
            text-align: center;
            text-decoration: none;
            border-radius: 5px;
            background: linear-gradient(to left, mediumslateblue 30%, #330867 80%);
            color: #333;
            transition: background-color 0.3s, color 0.3s;
            cursor: pointer;
            margin-bottom: 1em;
        }

            .button:hover {
                background-color: #333;
                color: #fff;
            }

        .full-width-button {
            width: 100%;
            margin-bottom: 1em;
        }

        .width-button {
            width: 49%;
            margin-bottom: 1em;
        }

        .height-buttom {
            height: 70px;
        }

        .Home2 {
            padding-top: 3em;
        }
    </style>
</head>
<body>
    <div class="Home">
        <div>
            <div class="app-name">

                <h1>Hello!</h1>
            </div>
        </div>
        <div class="Home2">
            <div>
                <a href="/SuperAdmin/Details/@id" class="button full-width-button height-buttom">
                    @ViewBag.UserName
                </a>
            </div>

            <div class="d-flex">
                <form asp-controller="SuperAdmin" asp-action="Options">
                    <button class="button width-button" type="submit" id="btnReport">Options</button>
                </form>

                <a href="/SuperAdmin/Display" class="button width-button">Accounts</a>

            </div>

            <div>
                <form asp-controller="SuperAdmin" asp-action="AboutOf">
                    <button class="button width-button" type="submit" id="btnReport">About</button>
                </form>
                <form asp-controller="SuperAdmin" asp-action="DownloadPDF">
                    <button class="button width-button" type="submit" id="btnReport">Report</button>
                </form>
            </div>

            <a href="/UserAuthentication/Logout" class="button full-width-button">
                Log Out
            </a>
        </div>
    </div>
</body>
</html>

ProyectoLenguajes/ProyectoLenguajes/Views/SuperAdmin/Options.cshtml
@using ProyectoLenguajes.Data;
@using Microsoft.AspNetCore.Mvc;
@using Microsoft.EntityFrameworkCore;
@using System.Security.Claims;
@model IEnumerable<ProyectoLenguajes.Models.ACCOUNT>
@{
    ViewData["Title"] = "Index";
    TestUCRContext db = new TestUCRContext();

    var userNameM = User.FindFirstValue(ClaimTypes.Name);//To get the username of current account
    var id = db.ACCOUNTs
    .Where(a => a.userName == userNameM)
    .Select(a => a.idAccount)
    .FirstOrDefault();//To get the id of de current account in our database
    var imge = db.ACCOUNTs
    .Where(a => a.userName == userNameM)
    .Select(a => a.img)
    .FirstOrDefault();//To get the img of the current account in our database
}
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Tangerine">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <title>Hello</title>
    <link rel="stylesheet" href="~/css/superadmin.css">

    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/jquery.slick/1.3.11/slick.css" />
    <link rel="stylesheet" type="text/css" href="slick/slick.css" />
    <link rel="stylesheet" type="text/css" href="slick/slick-theme.css" />
</head>

<body>
    <header>

        <div class="container">
            <h2 class="title">Hello!</h2>

            <!--NAVBAR-->
            <nav class="navbar navbar-expand-sm navbar navbar-light">

                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#opciones" style="background-color: #DDE9F8">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="opciones">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link active" href="/SuperAdmin/Home" style="color: #ffffff;">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/SuperAdmin/Details/@id" style="color: #ffffff;">Profile</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/SuperAdmin/AboutOf" style="color: #ffffff;">About Of</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/SuperAdmin/Display" style="color: #ffffff;">Accounts</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/UserAuthentication/Logout" style="color: #ffffff;">Log Out</a>
                        </li>
                    </ul>
                </div>
            </nav>
        </div>
    </header>

<hr />

<div class="table-responsive">
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.email)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.roll)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.userName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.password)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.email)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.roll)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.userName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.password)
                    </td>
                    <td>
                            <form asp-controller="SuperAdmin" asp-action="AddAdminPrivilege" method="post">
                                <input type="hidden" name="userName" value="@item.userName" />
                                <button class="btn btn-success" type="submit" >Allow</button>
                            </form>
                            <form asp-controller="SuperAdmin" asp-action="RemoveAdminPrivilege" method="post">
                                <input type="hidden" name="userName" value="@item.userName" />
                                <button class="btn btn-danger" type="submit">Deny</button>
                            </form>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

    <!--JS-->
    <script type="text/javascript" src="//code.jquery.com/jquery-1.11.0.min.js"></script>
    <script type="text/javascript" src="//code.jquery.com/jquery-migrate-1.2.1.min.js"></script>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>

    <!--To message success or deny-->
    <script>
        $('.btn-success').click(function () {
            swal("Allow", "Now this account is admin", "success")

            $('.textC').val("");
            $('.textS').val(0);
        });
        $('.btn-danger').click(function () {
            swal("Deny", "Now this account no longer has admin permissions", "error")

            $('.textC').val("");
            $('.textS').val(0);
        });
    </script>

</body>